id = "objectscript"
name = "InterSystems ObjectScript"
version = "1.3.0"
schema_version = 1
authors = ["Dave McCaldon <davem@intersystems.com>","Hannah Kimura <hannah.kimura@intersystems.com>"]
description = "InterSystems IRIS ObjectScript Extension"
repository = "https://github.com/intersystems/zed-objectscript"

[grammars.objectscript_udl]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
commit = "e492601cb5b4564fdf41e5a1800432a3ee4cf74f"
path = "udl"

[grammars.objectscript_routine]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
commit = "e492601cb5b4564fdf41e5a1800432a3ee4cf74f"
path = "objectscript_routine"

[grammars.objectscript]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
commit = "e492601cb5b4564fdf41e5a1800432a3ee4cf74f"
path = "objectscript"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "5000ae8f22d11fbe93939b05c1e37cf21117162d"
path = "xml"
