[workspace]
members = [".", "crates/objectscript-core"]

[package]
name = "objectscript-lsp"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Language Server Protocol for ObjectScript"

[dependencies]
objectscript-core = { path = "crates/objectscript-core" }
tower-lsp = "0.20.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "fs"] }
tree-sitter = "0.26.6"
tree-sitter-objectscript = "1.9.16"
tree-sitter-objectscript-routine = "1.9.16"
tree-sitter-objectscript-playground = "1.9.16"
tree-sitter-xml = "0.7.0"
serde = "1.0.228"
serde_json = "1.0.145"
parking_lot = "0.12.5"
walkdir = "2.5.0"
