name = "ObjectScript XML"
grammar = "xml"
path_suffixes = ["xml"]
first_line_pattern = '^<.*xml'
block_comment = ["<!-- ", " -->"]
brackets = [{ start = "<", end = ">", close = true, newline = true }]
